name: Build and Deploy
on:
  release:
    types:
      - created
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: |
          npm install
      - name: Set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=seconds)" >> ${GITHUB_ENV}
      - name: Build
        run: |
          npm run build
          rm -f public/openmargonem.bundle.js
          sed -i "s/__version__/${{ github.ref_name }}/g" public/openmargonem.user.js
          sed -i "s/__compiled_at__/$RELEASE_DATE/g" public/openmargonem.user.js
          cp public/openmargonem.user.js public/openmargonem.${{ github.ref_name }}.user.js
          mv public/openmargonem.user.js public/openmargonem.latest.user.js
      - name: Deploy scripts
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          clean: false

      - name: build index.js
        run: |
          mkdir index
          cd index
          echo "<html><body style='font-size: xx-large;'><h1><b>OpenMargonem version listing</b></h1>" > index.html
          echo "<a href='./openmargonem.latest.user.js'>openmargonem.latest.user.js</a><br/>" >> index.html
          for tag in $(git tag --sort=-creatordate)
          do
            echo "<a href='./openmargonem.${tag}.user.js'>openmargonem.${tag}.user.js</a><br/>" >> index.html
          done
          echo "</body></html>" >> index.html
      - name: Deploy index.html
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: index
          clean: false
      - name: Release assets upload
        uses: softprops/action-gh-release@v2
        with:
          files: public/openmargonem.${{ github.ref_name }}.user.js
